/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employees;

import Exceptions.InvalidMailException;
import Exceptions.InvalidPhoneException;
import Exceptions.InvalidSalaryException;
import GuiList.Requireable;
import GuiList.Showable;
import GuiList.Updatable;
import Utils.UtilDate;
import Utils.UtilGui;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author llean
 */
public class FrmModifyEmployee extends javax.swing.JFrame implements Updatable,Requireable,Showable {
    private static Employee employee;
    private static EmployeeList list;
    /**
     * Creates new form FrmModifyEmployee
     */
    public FrmModifyEmployee(Employee employee,EmployeeList list) {
        this.employee = employee;
        this.list = list;
        initComponents();
        showPosition();
        showData();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        txtBirthdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbPosition = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 525));
        setMinimumSize(new java.awt.Dimension(800, 525));
        setPreferredSize(new java.awt.Dimension(800, 525));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 525));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 39, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar Empleado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 50));

        btnModify.setBackground(new java.awt.Color(255, 255, 255));
        btnModify.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnModify.setForeground(new java.awt.Color(0, 0, 0));
        btnModify.setText("Modificar");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 200, -1));

        btnGoBack.setBackground(new java.awt.Color(255, 255, 255));
        btnGoBack.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(0, 0, 0));
        btnGoBack.setText("Regresar");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 210, -1));

        txtBirthdate.setEditable(false);
        txtBirthdate.setBackground(new java.awt.Color(255, 255, 255));
        txtBirthdate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtBirthdate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 200, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nacimiento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cedula");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        txtSalary.setBackground(new java.awt.Color(255, 255, 255));
        txtSalary.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSalary.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 190, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Salario");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        txtMail.setBackground(new java.awt.Color(255, 255, 255));
        txtMail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtMail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        txtPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtPhone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhone.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 190, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        cmbPosition.setBackground(new java.awt.Color(255, 255, 255));
        cmbPosition.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cmbPosition.setForeground(new java.awt.Color(0, 0, 0));
        cmbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPosition.setSelectedIndex(-1);
        jPanel1.add(cmbPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 210, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Puesto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/27-Edit_Text_256x256_35395.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        update();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
    FrmEmployee frmEmployee = new FrmEmployee();
    frmEmployee.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModifyEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModifyEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModifyEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModifyEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModifyEmployee(employee, list).setVisible(true);
            }
        });
    }

    
    private void showPosition() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (EmployeePosition position : EmployeePosition.values()) {
            model.addElement(position);
        }
        cmbPosition.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox<String> cmbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBirthdate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        if(validateRequiere()) {
        String phone = txtPhone.getText();
        String mail =txtMail.getText();
        EmployeePosition position = (EmployeePosition) cmbPosition.getSelectedItem();
        Double salary = Double.valueOf(txtSalary.getText());
        try {
            list.updateEmployee(employee.getId(), phone, mail, position, salary);
            FrmEmployee frmEmployee = new FrmEmployee();
            frmEmployee.setVisible(true);
            this.dispose();
        } catch (InvalidPhoneException | InvalidMailException | InvalidSalaryException e) {
            UtilGui.showErrorMessage(this, e.getMessage(), "error");
        }
        }else{
            UtilGui.showErrorMessage(this, "faltan datos requeridos", "error");
        }
    }

    @Override
    public boolean validateRequiere() {
       return UtilGui.validateRequiere(txtPhone,txtMail,txtSalary);
    }

    @Override
    public void showData() {
        txtId.setText(employee.getId());
        txtName.setText(employee.getName());
        txtBirthdate.setText(UtilDate.toString(employee.getBirthday()));
        txtPhone.setText(employee.getPhone());
        txtMail.setText(employee.getMail());
        txtSalary.setText(Double.toString(employee.getSalary()));
        cmbPosition.setSelectedItem(employee.getPosition());
    }
}
