/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employees;

import Exceptions.InvalidMailException;
import Exceptions.InvalidPhoneException;
import Exceptions.InvalidSalaryException;
import GuiList.Requireable;
import GuiList.Showable;
import GuiList.Updatable;
import Utils.UtilDate;
import Utils.UtilGui;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author llean
 */
public class FrmModifyEmployee extends javax.swing.JFrame implements Updatable,Requireable,Showable {
    private static Employee employee;
    private static EmployeeList list;
    /**
     * Creates new form FrmModifyEmployee
     */
    public FrmModifyEmployee(Employee employee,EmployeeList list) {
        this.employee = employee;
        this.list = list;
        initComponents();
        showPosition();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        txtBirthdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbPosition = new javax.swing.JComboBox<>();
        txtPhone = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 39, -1, -1));

        jLabel4.setText("Nacimiento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 178, -1, -1));

        btnModify.setText("Modificar");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 252, -1, -1));

        txtBirthdate.setEditable(false);
        getContentPane().add(txtBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 206, 100, -1));

        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 78, -1, -1));

        btnGoBack.setText("Regresar");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 252, -1, -1));

        jLabel6.setText("Correo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));
        getContentPane().add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Modificar Empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 22, -1, 50));

        txtId.setEditable(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, 100, -1));

        jLabel7.setText("Puesto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel8.setText("Salario");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 128, -1, -1));
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, -1));

        txtName.setEditable(false);
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, 100, -1));

        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 77, -1, -1));

        cmbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPosition.setSelectedIndex(-1);
        getContentPane().add(cmbPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 100, -1));

        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        update();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
    FrmEmployee frmEmployee = new FrmEmployee();
    frmEmployee.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModifyEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModifyEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModifyEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModifyEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModifyEmployee(employee, list).setVisible(true);
            }
        });
    }

    
    private void showPosition() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (EmployeePosition position : EmployeePosition.values()) {
            model.addElement(position);
        }
        cmbPosition.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox<String> cmbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBirthdate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        if(validateRequiere()) {
        String phone = txtPhone.getText();
        String mail =txtMail.getText();
        EmployeePosition position = (EmployeePosition) cmbPosition.getSelectedItem();
        Double salary = Double.valueOf(txtSalary.getText());
        try {
            list.updateEmployee(employee.getId(), phone, mail, position, salary);
            FrmEmployee frmEmployee = new FrmEmployee();
            frmEmployee.setVisible(true);
            this.dispose();
        } catch (InvalidPhoneException | InvalidMailException | InvalidSalaryException e) {
            UtilGui.showErrorMessage(this, e.getMessage(), "error");
        }
        }else{
            UtilGui.showErrorMessage(this, "faltan datos requeridos", "error");
        }
    }

    @Override
    public boolean validateRequiere() {
       return UtilGui.validateRequiere(txtPhone,txtMail,txtSalary);
    }

    @Override
    public void showData() {
        txtId.setText(employee.getId());
        txtName.setText(employee.getName());
        txtBirthdate.setText(UtilDate.toString(employee.getBirthday()));
        txtPhone.setText(employee.getPhone());
        txtMail.setText(employee.getMail());
        txtSalary.setText(Double.toString(employee.getSalary()));
        cmbPosition.setSelectedItem(employee.getPosition());
    }
}
