/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vehicles;

import Exceptions.InvalidPlateException;
import Exceptions.InvalidYearException;
import Utils.UtilDate;
import Utils.UtilGui;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import GuiList.Requireable;
import GuiList.Showable;
import GuiList.Updatable;

/**
 *
 * @author rodol
 */
public class DiaUpdateVehicle extends javax.swing.JDialog implements Requireable, Showable, Updatable {
        private static Vehicle vehicle;
        private static VehicleManager manager;
    /**
     * Creates new form DiaUpdateVehicle
     */
    public DiaUpdateVehicle(java.awt.Dialog parent, boolean modal,Vehicle vehicle, VehicleManager manager) {
        super(parent, modal);
        this.vehicle = vehicle;
        this.manager = manager;
        initComponents();
        this.setLocationRelativeTo(parent);
        showTypes();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgStates = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbRented = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtYear = new javax.swing.JFormattedTextField();
        rbMaintenance = new javax.swing.JRadioButton();
        txtType = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPlate = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        rbAvailable = new javax.swing.JRadioButton();
        btnUpdate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(974, 544));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Año");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        rbRented.setBackground(new java.awt.Color(255, 255, 255));
        btgStates.add(rbRented);
        rbRented.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbRented.setForeground(new java.awt.Color(0, 0, 0));
        rbRented.setText("Rentado");
        jPanel1.add(rbRented, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 98, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rentedIcon.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 30, 30));

        txtYear.setEditable(false);
        txtYear.setBackground(new java.awt.Color(255, 255, 255));
        txtYear.setForeground(new java.awt.Color(0, 0, 0));
        txtYear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 200, 40));

        rbMaintenance.setBackground(new java.awt.Color(255, 255, 255));
        btgStates.add(rbMaintenance);
        rbMaintenance.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbMaintenance.setForeground(new java.awt.Color(0, 0, 0));
        rbMaintenance.setText("Mantenimiento");
        jPanel1.add(rbMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, -1, -1));

        txtType.setBackground(new java.awt.Color(255, 255, 255));
        txtType.setForeground(new java.awt.Color(0, 0, 0));
        txtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtType.setSelectedIndex(-1);
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        jPanel1.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 160, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/availableIcon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tipo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maintenanceIcon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, -1, 30));

        txtPlate.setEditable(false);
        txtPlate.setBackground(new java.awt.Color(255, 255, 255));
        txtPlate.setForeground(new java.awt.Color(0, 0, 0));
        txtPlate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 200, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carIcon.png"))); // NOI18N
        jLabel1.setText("Actualizar Vehiculo");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setPreferredSize(new java.awt.Dimension(430, 58));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 700, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Placa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        txtBrand.setEditable(false);
        txtBrand.setBackground(new java.awt.Color(255, 255, 255));
        txtBrand.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtBrand.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 200, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Modelo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        txtModel.setBackground(new java.awt.Color(255, 255, 255));
        txtModel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtModel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 200, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelIcon.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 110, 70));

        rbAvailable.setBackground(new java.awt.Color(255, 255, 255));
        btgStates.add(rbAvailable);
        rbAvailable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbAvailable.setForeground(new java.awt.Color(0, 0, 0));
        rbAvailable.setText("Disponible");
        jPanel1.add(rbAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 110, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/updateIcon.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 110, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GrupoDypurConjunto.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 340, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int decision = UtilGui.showConfirmMessage(this, "¿Estas seguro que deseas cancelar la actualizacion del vehiculo?", "Confirmar Eliminacion");
        if (decision == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

     private void showTypes() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (VehicleType type : VehicleType.values()) {
            model.addElement(type);
        }
        txtType.setModel(model);
    }

    @Override
    public boolean validateRequiere() {
       return UtilGui.validateRequiere(txtModel);
    }

    @Override
    public void update() {
        if (validateRequiere()) {
            String newModel = txtModel.getText();
            VehicleType newType = (VehicleType) txtType.getSelectedItem();
            VehicleState newState = null;

            if (rbAvailable.isSelected()) {
                newState = VehicleState.AVAILABLE;
            } else if (rbRented.isSelected()) {
                newState = VehicleState.RENTED;
            } else if (rbMaintenance.isSelected()) {
                newState = VehicleState.INMAINTENANCE;
            }

            try {
                Vehicle updatedVehicle = new Vehicle(vehicle.getPlate(), vehicle.getBrand(), newModel, vehicle.getYear(), newType);
                updatedVehicle.setState(newState);

                manager.updateVehicle(updatedVehicle);

                this.dispose();
            } catch (InvalidPlateException | InvalidYearException e) {
                UtilGui.showErrorMessage(this, "Error al obtener el vehiculo: " + e.getMessage(), "Error");
            }
        } else {
            UtilGui.showErrorMessage(this, "Faltan datos requeridos", "Error");
        }
    }

    @Override
    public void showData() {
        if (vehicle == null) {
            UtilGui.showErrorMessage(this, "Debe especificar el vehículo a actualizar", "Error");
            return;
        }
        
        if (vehicle.getState() == VehicleState.AVAILABLE) {
            rbAvailable.setSelected(true);
        } else if (vehicle.getState() == VehicleState.RENTED) {
            rbRented.setSelected(true);
        } else if (vehicle.getState() == VehicleState.INMAINTENANCE) {
            rbMaintenance.setSelected(true);
        }

        txtPlate.setText(vehicle.getPlate());
        txtBrand.setText(vehicle.getBrand());
        txtModel.setText(vehicle.getModel());
        txtYear.setText(String.valueOf(vehicle.getYear()));
        txtType.setSelectedItem(vehicle.getType());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaUpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaUpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaUpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaUpdateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiaUpdateVehicle dialog = new DiaUpdateVehicle(new javax.swing.JDialog(), true, vehicle, manager);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgStates;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbAvailable;
    private javax.swing.JRadioButton rbMaintenance;
    private javax.swing.JRadioButton rbRented;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtModel;
    private javax.swing.JFormattedTextField txtPlate;
    private javax.swing.JComboBox<String> txtType;
    private javax.swing.JFormattedTextField txtYear;
    // End of variables declaration//GEN-END:variables

    
}
